// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProyectoRankingEmpresas.Model;

namespace ProyectoRankingEmpresas.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20201121033112_primeram")]
    partial class primeram
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("EntityModel.MClass.ActionU", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.Property<string>("Valor")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Actions");
                });

            modelBuilder.Entity("EntityModel.MClass.GrupoUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("character varying(55)")
                        .HasMaxLength(55);

                    b.Property<string>("UsuarioCreation")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GrupoUser");
                });

            modelBuilder.Entity("EntityModel.MClass.UserSys", b =>
                {
                    b.Property<string>("Guid")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("GrupuserId")
                        .HasColumnType("integer");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("LastName")
                        .HasColumnType("character varying(55)")
                        .HasMaxLength(55);

                    b.Property<string>("Name")
                        .HasColumnType("character varying(55)")
                        .HasMaxLength(55);

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("user")
                        .HasColumnType("text");

                    b.HasKey("Guid");

                    b.HasIndex("GrupuserId")
                        .IsUnique();

                    b.ToTable("User");
                });

            modelBuilder.Entity("EntityModel.MClass.ActionU", b =>
                {
                    b.HasOne("EntityModel.MClass.GrupoUser", "Group")
                        .WithMany("Acciones")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EntityModel.MClass.UserSys", b =>
                {
                    b.HasOne("EntityModel.MClass.GrupoUser", "grupouser")
                        .WithOne("User")
                        .HasForeignKey("EntityModel.MClass.UserSys", "GrupuserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
